### ISSUE TITLE
Torture-testing Backup and Archive Programs: Things You Ought to Know But Probably Would Rather Not

### ISSUE THREAD

**Issue by braian87b** [laurent22/rsync-time-backup#193]
to see: http://www.coredumps.de/doc/dump/zwicky/testdump.doc.html

**Comment by reactive-firewall** [comment]
Oh this looks fun ... I'll see about hacking out a test script for these if no one else is working on it
🤔  ... um ... but first ... *IS* anyone already working on this? ... if so stop me from re-inventing

**Comment by reactive-firewall** [comment]
I think this calls for some CI testing (🎉 _I'm so excited_)

So that it's documented somewhere:
CI Testing is great for ensuring code works and changes don't introduce regressions to tested code _(caveat: test coverage)_
### Issues that this could help:
- [ ] laurent22/rsync-time-backup#190
- [ ] laurent22/rsync-time-backup#181
- [ ] laurent22/rsync-time-backup#183
- [ ] laurent22/rsync-time-backup#175 _?_
- [ ] laurent22/rsync-time-backup#172
- [ ] laurent22/rsync-time-backup#157
- [ ] laurent22/rsync-time-backup#116
- [ ] **laurent22/rsync-time-backup#115**
- [ ] **laurent22/rsync-time-backup#89**

most basic test logic: use github's actions (I'm on it)

Tests to start creating:
- [ ] Static tests:
  - [ ] A file with a large hole in it.
  - [ ] A file that contains a hole and a block's worth of nulls.
  - [ ] Files with funny characters in their file names.
  - [ ] 1025 hard links to the same file.
  - [ ] 2911 hard links to different files.
  - [ ] Files with long names.
  - [ ] Symbolic links to long names.
  - [ ] Symbolic links to names with funny characters in them.
  - [ ] Unreadable and unwriteable files.
  - [ ] Unreadable and unwriteable directories with normal files in them.
  - [ ] A named pipe.
  - [ ] A device.

**Comment by reactive-firewall** [comment]
😥 No one stopped me before I got to starting on this issue .... 🤓 SO I prepared a PR #205 for testing ... reviews welcome!
